# Generated by Django 3.2.9 on 2021-11-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_quizzy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Seçenek', 'verbose_name_plural': 'Seçenekler'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Soru', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizzy',
            options={'ordering': ['id'], 'verbose_name': 'Sınav', 'verbose_name_plural': 'Quizzies'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_right',
            field=models.BooleanField(default=False, verbose_name='Doğru Seçenek mi?'),
        ),
    ]
