# Generated by Django 3.2.9 on 2021-11-28 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_quizzy_app', '0002_auto_20211128_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Question'),
            preserve_default=False,
        ),
    ]
