# Generated by Django 3.2.9 on 2021-11-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_quizzy_app', '0003_auto_20211128_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='quiz_topic',
        ),
        migrations.AlterField(
            model_name='quizzy',
            name='title',
            field=models.CharField(default='New Quiz', max_length=255, verbose_name='Quiz Topic'),
        ),
    ]
