# Generated by Django 3.2.9 on 2021-12-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_quizzy_app', '0006_alter_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_of_answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Explanation'),
        ),
    ]
